// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5112.Robot2016DrivetrainEssentials;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;
import edu.wpi.first.wpilibj.TalonSRX;
import edu.wpi.first.wpilibj.Victor;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController drivetraindrivetrainLeft1;
    public static SpeedController drivetraindrivetrainLeft2;
    public static SpeedController drivetraindrivetrainRight1;
    public static SpeedController drivetraindrivetrainRight2;
    public static RobotDrive drivetraindrivetrain;
    public static SpeedController shootershooterMotorLeft;
    public static SpeedController shootershooterMotorRight;
    public static SpeedController intakeintakeMotor;
    public static SpeedController armarmMotor;
    public static SpeedController kickerkickerMotor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        drivetraindrivetrainLeft1 = new TalonSRX(0);
        LiveWindow.addActuator("Drivetrain", "drivetrainLeft1", (TalonSRX) drivetraindrivetrainLeft1);
        
        drivetraindrivetrainLeft2 = new TalonSRX(5);
        LiveWindow.addActuator("Drivetrain", "drivetrainLeft2", (TalonSRX) drivetraindrivetrainLeft2);
        
        drivetraindrivetrainRight1 = new TalonSRX(2);
        LiveWindow.addActuator("Drivetrain", "drivetrainRight1", (TalonSRX) drivetraindrivetrainRight1);
        
        drivetraindrivetrainRight2 = new TalonSRX(3);
        LiveWindow.addActuator("Drivetrain", "drivetrainRight2", (TalonSRX) drivetraindrivetrainRight2);
        
        drivetraindrivetrain = new RobotDrive(drivetraindrivetrainLeft1, drivetraindrivetrainLeft2,
              drivetraindrivetrainRight1, drivetraindrivetrainRight2);
        
        drivetraindrivetrain.setSafetyEnabled(true);
        drivetraindrivetrain.setExpiration(0.1);
        drivetraindrivetrain.setSensitivity(0.5);
        drivetraindrivetrain.setMaxOutput(1.0);
        drivetraindrivetrain.setInvertedMotor(RobotDrive.MotorType.kFrontLeft, true);
        drivetraindrivetrain.setInvertedMotor(RobotDrive.MotorType.kRearLeft, true);
        drivetraindrivetrain.setInvertedMotor(RobotDrive.MotorType.kFrontRight, true);
        drivetraindrivetrain.setInvertedMotor(RobotDrive.MotorType.kRearRight, true);
        shootershooterMotorLeft = new TalonSRX(4);
        LiveWindow.addActuator("Shooter", "shooterMotorLeft", (TalonSRX) shootershooterMotorLeft);
        
        shootershooterMotorRight = new Talon(1);
        LiveWindow.addActuator("Shooter", "shooterMotorRight", (Talon) shootershooterMotorRight);
        
        intakeintakeMotor = new Victor(19);
        LiveWindow.addActuator("Intake", "intakeMotor", (Victor) intakeintakeMotor);
        
        armarmMotor = new Victor(18);
        LiveWindow.addActuator("Arm", "armMotor", (Victor) armarmMotor);
        
        kickerkickerMotor = new Victor(17);
        LiveWindow.addActuator("Kicker", "kickerMotor", (Victor) kickerkickerMotor);
        

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
